/* Generated By:JavaCC: Do not edit this line. ArithmeticInterpreter.java */
import java.util.HashMap;

public class ArithmeticInterpreter implements ArithmeticInterpreterConstants {
  private HashMap variables = new HashMap();
  private HashMap arrays = new HashMap();

  public ArithmeticInterpreter() {
    this(System.in);
  }

  private double getVariable(String name) throws ParseException {
    if (!variables.containsKey(name)) {
      throw new ParseException("Variable '" + name + "' not defined");
    }
    return (Double) variables.get(name);
  }

  private double getArrayElement(String name, int index) throws ParseException {
    if (!arrays.containsKey(name)) {
      throw new ParseException("Array '" + name + "' not defined");
    }
    double[] arr = (double[])arrays.get(name);
    if (index < 0 || index >= arr.length) {
      throw new ParseException("Array index out of bounds: " + index);
    }
    return arr[index];
  }

  private double callFunction(String name, double arg) throws ParseException {
    switch(name) {
      case "sin": return Math.sin(arg);
      case "cos": return Math.cos(arg);
      case "sqrt": return Math.sqrt(arg);
      case "abs": return Math.abs(arg);
      case "log": return Math.log(arg);
      default:
        throw new ParseException("Function '" + name + "' not defined");
    }
  }

  public static void main(String[] args) throws ParseException {
    ArithmeticInterpreter parser = new ArithmeticInterpreter();
    System.out.println("Arithmetic Interpreter with Variables, Functions & Arrays");
    System.out.println("Available variables: x=10, y=5");
    System.out.println("Available array: arr[0..4] = {1,2,3,4,5}");
    System.out.println("Available functions: sin, cos, sqrt, abs, log");
    System.out.println("Examples: x + y, sin(x), arr[2], x * (y - 3)\n");

    while (true) {
      try {
        System.out.print("> ");
        double result = parser.Expression();
        System.out.println("Result: " + result);
        parser.ReInit(System.in);
      } catch (ParseException e) {
        System.out.println("Error: " + e.getMessage());
        parser.ReInit(System.in);
      } catch (Exception e) {
        break;
      }
    }
  }

/* Grammar Rules following the specified structure */

// ExprArith => ExprArith + EltArith | ExprArith - EltArith | EltArith
  final public double Expression() throws ParseException {
  double val;
    val = ExprArith();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EOL:
      jj_consume_token(EOL);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    {if (true) return val;}
    throw new Error("Missing return statement in function");
  }

  final public double ExprArith() throws ParseException {
  double left, right;
    left = EltArith();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        right = EltArith();
      left += right;
        break;
      case MINUS:
        jj_consume_token(MINUS);
        right = EltArith();
      left -= right;
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

// EltArith => EltArith * TermArith | EltArith / TermArith | TermArith
  final public double EltArith() throws ParseException {
  double left, right;
    left = TermArith();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
      case DIVIDE:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
        jj_consume_token(MULTIPLY);
        right = TermArith();
      left *= right;
        break;
      case DIVIDE:
        jj_consume_token(DIVIDE);
        right = TermArith();
      if (right == 0)
        {if (true) throw new ParseException("Division by zero");}
      left /= right;
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

// TermArith => -ValArith | ValArith
  final public double TermArith() throws ParseException {
  double val;
  boolean negative = false;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      jj_consume_token(MINUS);
             negative = true;
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    val = ValArith();
    {if (true) return negative ? -val : val;}
    throw new Error("Missing return statement in function");
  }

// ValArith => VariableArith | AppelFuncArith | (ExprArith) | Identifiant[ExprArith]
  final public double ValArith() throws ParseException {
  double val;
  Token t;
  int index;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
      // Number literal
        t = jj_consume_token(NUMBER);
    {if (true) return Double.parseDouble(t.image);}
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      val = ExprArith();
      jj_consume_token(RPAREN);
    {if (true) return val;}
      break;
    case IDENTIFIER:
      // Function call or variable or array access
        t = jj_consume_token(IDENTIFIER);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
        jj_consume_token(LPAREN);
        val = ExprArith();
        jj_consume_token(RPAREN);
      {if (true) return callFunction(t.image, val);}
        break;
      case LBRACKET:
        jj_consume_token(LBRACKET);
        val = ExprArith();
        jj_consume_token(RBRACKET);
      {if (true) return getArrayElement(t.image, (int)val);}
        break;
      default:
        jj_la1[6] = jj_gen;
      {if (true) return getVariable(t.image);}
      }
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public ArithmeticInterpreterTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[8];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4000,0xc0,0xc0,0x300,0x300,0x80,0x1400,0x430,};
   }

  /** Constructor with InputStream. */
  public ArithmeticInterpreter(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ArithmeticInterpreter(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ArithmeticInterpreterTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ArithmeticInterpreter(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ArithmeticInterpreterTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ArithmeticInterpreter(ArithmeticInterpreterTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ArithmeticInterpreterTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[15];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 8; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 15; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
