PARSER_BEGIN(Compiler)
public class Compiler {
  public static void main(String[] args) {
    Compilateur parser = new Compilateur(System.in);
    Compilateur.Programme();
    System.out.println("OMG CA MARCHE");
  }
}
PARSER_END(Compiler)

SKIP : {
  " " | "\t"
}

// ############ Terminaux / Types ############

TOKEN : {
  <STRING: (<CHAR>)+ >
| <CHAR: <LETTRE> | <CHIFFRE> | <SYMBOLE> >
| <LETTRE: ["a"-"z","A"-"Z"]>
| <CHIFFRE: ["0"-"9"]>
| <#SYMBOLE: " " | "!" | "\"" | "#" | "$" | "%" | "&" | "'" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "[" | "\\" | "]" | "^" | "_" | "`" | "{" | "|" | "}" | "~">

| <BOOLEAN: "true" | "false" >
| <VARIABLELOG: <BOOLEAN> | <IDENTIFIANT> >

| <NOMBRE: <INT> | <FLOAT> >
| <INT: (<CHIFFRE>)* >
| <FLOAT: <INT> | <INT>  "." <INT> >
| <VARIABLEARITH: <NOMBRE> | <IDENTIFIANT> >

  // <IDENTIFIANT: <LETTRE> (<SUITEIDENTIFIANT>)* >
  // <SUITEIDENTIFIANT: <LETTRE> <SUITEIDENTIFIANT> | <CHIFFRE> <SUITEIDENTIFIANT> | "_" <SUITEIDENTIFIANT> >

|  <IDENTIFIANT: <LETTRE> (<LETTRE> | <CHIFFRE> | "_")*>

}

// ############ Listes ############

// void IntListe() : {}
// {
//   "[" (EltInt())+ "]
// }
// void EltInt() : {}
// {
//  <INT> (<"," <INT>)*
//}

TOKEN : {
  <INTLISTE: "[" (<INT> ("," <INT>)*)+ "]" >
| <STRINGLISTE: "[" (<STRING> ("," <STRING>)*)+ "]" >
| <FLOATLISTE: "[" (<FLOAT> ("," <FLOAT>)*)+ "]" >
| <BOOLLISTE: "[" (<BOOLEAN> ("," <BOOLEAN>)*)+ "]" >
}

// ############ Logique ############

TOKEN : {
  <EXPRLOG: <ELTLOG> ("or" <ELTLOG>)* >
| <ELTLOG: <TERMELOG> ("and" <TERMELOG>)* >
| <TERMELOG: ("!" <VALOG>) | <VALOG> >
| <VALOG: <VARIABLELOG>  | <COMP> | <IDENTIFIANT> "[" <EXPARITH> ("," <EXPARITH>)* "]" > // "("<EXPRLOG>")" | <APPELFUNCLOG>
}


// ############ Comparaison ############

TOKEN : {
  <COMP: (<EXPARITH> <OPCOMP> <EXPARITH>) | (<EXPARITH> <OPEQ> <EXPARITH>) | (<EXPRSTRING> <OPEQ> <EXPRSTRING>) >
| <OPEQ: "=" | "!=" >
| <OPCOMP: ">" | "<" | ">=" | "<=" >
}

// ############ Appels de fonction ############
/*
TOKEN : {
  <APPELFUNC: <IDENTIFIANT> "(" (<LISTARGS>)? ")" >
| <LISTARGS: <PARAM> ("," <PARAM>)? >
| <PARAM: <EXPARITH> | <EXPRLOG> | <EXPRSTRING> | <IDENTIFIANT> >


// Appels de fonction spécifiques par type de retour
| <APPELFUNCLOG: <IDENTIFIANT> "(" (<LISTARGS>)? ")" >
| <APPELFUNCARITH: <IDENTIFIANT> "(" (<LISTARGS>)? ")" >
| <APPELFUNCSTRING: <IDENTIFIANT> "(" (<LISTARGS>)? ")" >

}*/

// ############ Appels de fonction ############

// Liste d'arguments
void ListArgs() : {}
{
  Param() ("," Param())*
}

// Un paramètre peut être n'importe quelle expression
void Param() : {}
{
  <EXPARITH> | <EXPRLOG> | <EXPRSTRING> | <IDENTIFIANT>
}

// Type de retour
void TypeRetour() : {}
{
  <NOMBRE> | <STRING> | <BOOLEAN> | <INTLISTE> | <STRINGLISTE> | <FLOATLISTE> | <BOOLLISTE>
}

// Fonction
void AppelFunc() : {}
{
  <IDENTIFIANT> "(" (ListArgs())? ")" ":" TypeRetour()
}

// ############ Appels de procédure ############
// Production pour appel de procédure (sans type de retour)
void AppelProc() : {}
{
  <IDENTIFIANT> "(" (ListArgs())? ")" ";"
}

