PARSER_BEGIN(Compiler)
public class Compiler {
  public static void main(String[] args) {
    Compilateur parser = new Compilateur(System.in);
    Compilateur.Programme();
    System.out.println("OMG CA MARCHE");
  }
}
PARSER_END(Compiler)

SKIP : {
  " " | "\t"
}

// ############ Terminaux / Types ############

TOKEN : {
  <STRING: (<CHAR>)+ >
| <CHAR: <LETTRE> | <CHIFFRE> | <SYMBOLE> >
| <LETTRE: ["a"-"z","A"-"Z"]>
| <CHIFFRE: ["0"-"9"]>
| <#SYMBOLE: " " | "!" | "\"" | "#" | "$" | "%" | "&" | "'" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "[" | "\\" | "]" | "^" | "_" | "`" | "{" | "|" | "}" | "~">

| <BOOLEAN: "true" | "false" >
| <VARIABLELOG: <BOOLEAN> | <IDENTIFIANT> >

| <NOMBRE: <INT> | <FLOAT> >
| <INT: (<CHIFFRE>)* >
| <FLOAT: <INT> | <INT>  "." <INT> >
| <VARIABLEARITH: <NOMBRE> | <IDENTIFIANT> >

  // <IDENTIFIANT: <LETTRE> (<SUITEIDENTIFIANT>)* >
  // <SUITEIDENTIFIANT: <LETTRE> <SUITEIDENTIFIANT> | <CHIFFRE> <SUITEIDENTIFIANT> | "_" <SUITEIDENTIFIANT> >

|  <IDENTIFIANT: <LETTRE> (<LETTRE> | <CHIFFRE> | "_")*>

}

// ############ Listes ############

// void IntListe() : {}
// {
//   "[" (EltInt())+ "]
// }
// void EltInt() : {}
// {
//  <INT> (<"," <INT>)*
//}

TOKEN : {
  <INTLISTE: "[" (<INT> ("," <INT>)*)+ "]" >
| <STRINGLISTE: "[" (<STRING> ("," <STRING>)*)+ "]" >
| <FLOATLISTE: "[" (<FLOAT> ("," <FLOAT>)*)+ "]" >
| <BOOLLISTE: "[" (<BOOLEAN> ("," <BOOLEAN>)*)+ "]" >
}

// ############ Logique ############

TOKEN : {
  <EXPRLOG: <ELTLOG> ("or" <ELTLOG>)* >
| <ELTLOG: <TERMELOG> ("and" <TERMELOG>)* >
| <TERMELOG: ("!" <VALOG>) | <VALOG> >
| <VALOG: <VARIABLELOG> | <APPELFUNCLOG> | <COMP> | <IDENTIFIANT> "[" <EXPARITH> ("," <EXPARITH>)* "]" > // "("<EXPRLOG>")"
}


// ############ Comparaison ############

TOKEN : {
  <COMP: (<EXPARITH> <OPCOMP> <EXPARITH>) | (<EXPARITH> <OPEQ> <EXPARITH>) | (<EXPRSTRING> <OPEQ> <EXPRSTRING>) >
| <OPEQ: "=" | "!=" >
| <OPCOMP: ">" | "<" | ">=" | "<=" >
}
