/* Generated By:JavaCC: Do not edit this line. Interpreter.java */
import java.util.*;
import java.io.*;

public class Interpreter implements InterpreterConstants {
  // Simple AST node classes as inner classes
  static class ASTNode {}

  static class Program extends ASTNode {
    List declarations;
    List functions;
    List procedures;
    Object main;
  }

  static class Block extends ASTNode {
    List statements;
  }

  static class VarDecl extends ASTNode {
    String type;
    List names;
  }

  static class Assignment extends ASTNode {
    String varName;
    Object index;
    Object value;
  }

  static class IfStmt extends ASTNode {
    Object condition;
    Object thenBlock;
    Object elseBlock;
  }

  static class WhileStmt extends ASTNode {
    Object condition;
    Object body;
  }

  static class PrintStmt extends ASTNode {
    Object expression;
  }

  static class ReturnStmt extends ASTNode {
    Object value;
  }

  static class FuncCall extends ASTNode {
    String name;
    List args;
  }

  static class FuncDef extends ASTNode {
    String name;
    String returnType;
    List params;
    Object body;
  }

  static class ProcDef extends ASTNode {
    String name;
    List params;
    Object body;
  }

  static class Param extends ASTNode {
    String type;
    String name;
  }

  static class BinaryExpr extends ASTNode {
    String operator;
    Object left;
    Object right;
  }

  static class UnaryExpr extends ASTNode {
    String operator;
    Object operand;
  }

  static class Variable extends ASTNode {
    String name;
    Object index;
  }

  static class Literal extends ASTNode {
    Object value;
  }

  static class ArrayLiteral extends ASTNode {
    List elements;
  }

  static class InputExpr extends ASTNode {}

  // Interpreter state
  private Map globalVars = new HashMap();
  private Map functions = new HashMap();
  private Map procedures = new HashMap();
  private Stack scopes = new Stack();
  private boolean hasReturned = false;
  private Object returnValue = null;

  // Helper methods
  private void pushScope() {
    scopes.push(new HashMap());
  }

  private void popScope() {
    if (!scopes.isEmpty()) scopes.pop();
  }

  private void setVar(String name, Object value) {
    if (!scopes.isEmpty()) {
      ((Map)scopes.peek()).put(name, value);
    } else {
      globalVars.put(name, value);
    }
  }

  private Object getVar(String name) {
    for (int i = scopes.size() - 1; i >= 0; i--) {
      Map scope = (Map)scopes.get(i);
      if (scope.containsKey(name)) {
        return scope.get(name);
      }
    }
    return globalVars.get(name);
  }

  private Object getDefaultValue(String type) {
    if (type.equals("int")) return Integer.valueOf(0);
    if (type.equals("float")) return Double.valueOf(0.0);
    if (type.equals("string")) return "";
    if (type.equals("boolean")) return Boolean.FALSE;
    if (type.equals("int[]")) return new ArrayList();
    if (type.equals("float[]")) return new ArrayList();
    if (type.equals("string[]")) return new ArrayList();
    if (type.equals("boolean[]")) return new ArrayList();
    return null;
  }

  // Execution methods
  private void executeProgram(Program program) {
    if (program.declarations != null) {
      for (int i = 0; i < program.declarations.size(); i++) {
        execute(program.declarations.get(i));
      }
    }

    if (program.functions != null) {
      for (int i = 0; i < program.functions.size(); i++) {
        FuncDef func = (FuncDef)program.functions.get(i);
        functions.put(func.name, func);
      }
    }

    if (program.procedures != null) {
      for (int i = 0; i < program.procedures.size(); i++) {
        ProcDef proc = (ProcDef)program.procedures.get(i);
        procedures.put(proc.name, proc);
      }
    }

    if (program.main != null) {
      execute(program.main);
    }
  }

  private Object execute(Object node) {
    if (node == null) return null;

    if (node instanceof Block) {
      return executeBlock((Block)node);
    } else if (node instanceof VarDecl) {
      return executeVarDecl((VarDecl)node);
    } else if (node instanceof Assignment) {
      return executeAssignment((Assignment)node);
    } else if (node instanceof IfStmt) {
      return executeIf((IfStmt)node);
    } else if (node instanceof WhileStmt) {
      return executeWhile((WhileStmt)node);
    } else if (node instanceof PrintStmt) {
      return executePrint((PrintStmt)node);
    } else if (node instanceof ReturnStmt) {
      return executeReturn((ReturnStmt)node);
    } else if (node instanceof FuncCall) {
      return executeFuncCall((FuncCall)node);
    } else if (node instanceof BinaryExpr) {
      return evaluateBinary((BinaryExpr)node);
    } else if (node instanceof UnaryExpr) {
      return evaluateUnary((UnaryExpr)node);
    } else if (node instanceof Variable) {
      return evaluateVariable((Variable)node);
    } else if (node instanceof Literal) {
      return ((Literal)node).value;
    } else if (node instanceof ArrayLiteral) {
      return evaluateArrayLiteral((ArrayLiteral)node);
    } else if (node instanceof InputExpr) {
      Scanner sc = new Scanner(System.in);
      return sc.nextLine();
    }

    return null;
  }

  private Object executeBlock(Block block) {
    pushScope();
    Object result = null;

    if (block.statements != null) {
      for (int i = 0; i < block.statements.size(); i++) {
        result = execute(block.statements.get(i));
        if (hasReturned) break;
      }
    }

    popScope();
    return result;
  }

  private Object executeVarDecl(VarDecl decl) {
    Object defaultValue = getDefaultValue(decl.type);
    for (int i = 0; i < decl.names.size(); i++) {
      String name = (String)decl.names.get(i);
      setVar(name, defaultValue);
    }
    return null;
  }

  private Object executeAssignment(Assignment assign) {
    Object value = execute(assign.value);

    if (assign.index != null) {
      Object array = getVar(assign.varName);
      if (array instanceof List) {
        int idx = ((Number)execute(assign.index)).intValue();
        List list = (List)array;
        while (list.size() <= idx) {
          list.add(getDefaultValueForArray(array));
        }
        list.set(idx, value);
      }
    } else {
      setVar(assign.varName, value);
    }

    return value;
  }

  private Object getDefaultValueForArray(Object array) {
    if (array instanceof List && !((List)array).isEmpty()) {
      Object first = ((List)array).get(0);
      if (first instanceof Integer) return Integer.valueOf(0);
      if (first instanceof Double) return Double.valueOf(0.0);
      if (first instanceof String) return "";
      if (first instanceof Boolean) return Boolean.FALSE;
    }
    return Integer.valueOf(0);
  }

  private Object executeIf(IfStmt ifStmt) {
    boolean cond = ((Boolean)execute(ifStmt.condition)).booleanValue();
    if (cond) {
      return execute(ifStmt.thenBlock);
    } else if (ifStmt.elseBlock != null) {
      return execute(ifStmt.elseBlock);
    }
    return null;
  }

  private Object executeWhile(WhileStmt whileStmt) {
    Object result = null;
    while (true) {
      boolean cond = ((Boolean)execute(whileStmt.condition)).booleanValue();
      if (!cond) break;
      result = execute(whileStmt.body);
      if (hasReturned) break;
    }
    return result;
  }

  private Object executePrint(PrintStmt print) {
    Object value = execute(print.expression);
    System.out.println(value);
    return null;
  }

  private Object executeReturn(ReturnStmt ret) {
    hasReturned = true;
    if (ret.value != null) {
      returnValue = execute(ret.value);
    } else {
      returnValue = null;
    }
    throw new RuntimeException("Return");
  }

  private Object executeFuncCall(FuncCall call) {
    System.out.println("Calling: " + call.name);
    return null;
  }

  private Object evaluateBinary(BinaryExpr expr) {
    Object left = execute(expr.left);
    Object right = execute(expr.right);

    if (expr.operator.equals("+")) {
      if (left instanceof Number && right instanceof Number) {
        return Double.valueOf(((Number)left).doubleValue() + ((Number)right).doubleValue());
      }
      return left.toString() + right.toString();
    } else if (expr.operator.equals("-")) {
      return Double.valueOf(((Number)left).doubleValue() - ((Number)right).doubleValue());
    } else if (expr.operator.equals("*")) {
      return Double.valueOf(((Number)left).doubleValue() * ((Number)right).doubleValue());
    } else if (expr.operator.equals("/")) {
      double divisor = ((Number)right).doubleValue();
      return divisor == 0 ? Double.valueOf(0) : Double.valueOf(((Number)left).doubleValue() / divisor);
    } else if (expr.operator.equals("and")) {
      return Boolean.valueOf(((Boolean)left).booleanValue() && ((Boolean)right).booleanValue());
    } else if (expr.operator.equals("or")) {
      return Boolean.valueOf(((Boolean)left).booleanValue() || ((Boolean)right).booleanValue());
    } else if (expr.operator.equals("=")) {
      if (left instanceof Number && right instanceof Number) {
        return Boolean.valueOf(((Number)left).doubleValue() == ((Number)right).doubleValue());
      }
      return Boolean.valueOf(left.equals(right));
    } else if (expr.operator.equals("!=")) {
      return Boolean.valueOf(!left.equals(right));
    } else if (expr.operator.equals("<")) {
      return Boolean.valueOf(((Number)left).doubleValue() < ((Number)right).doubleValue());
    } else if (expr.operator.equals(">")) {
      return Boolean.valueOf(((Number)left).doubleValue() > ((Number)right).doubleValue());
    } else if (expr.operator.equals("<=")) {
      return Boolean.valueOf(((Number)left).doubleValue() <= ((Number)right).doubleValue());
    } else if (expr.operator.equals(">=")) {
      return Boolean.valueOf(((Number)left).doubleValue() >= ((Number)right).doubleValue());
    }
    return null;
  }

  private Object evaluateUnary(UnaryExpr expr) {
    Object value = execute(expr.operand);
    if (expr.operator.equals("!")) {
      return Boolean.valueOf(!((Boolean)value).booleanValue());
    } else if (expr.operator.equals("-")) {
      return Double.valueOf(-((Number)value).doubleValue());
    }
    return value;
  }

  private Object evaluateVariable(Variable var) {
    Object value = getVar(var.name);
    if (value == null) {
      return Integer.valueOf(0);
    }

    if (var.index != null && value instanceof List) {
      int idx = ((Number)execute(var.index)).intValue();
      List list = (List)value;
      if (idx >= 0 && idx < list.size()) {
        return list.get(idx);
      }
      return getDefaultValueForArray(value);
    }

    return value;
  }

  private Object evaluateArrayLiteral(ArrayLiteral array) {
    List result = new ArrayList();
    if (array.elements != null) {
      for (int i = 0; i < array.elements.size(); i++) {
        result.add(execute(array.elements.get(i)));
      }
    }
    return result;
  }

  public static void main(String[] args) throws Exception {
    if (args.length == 0) {
      System.out.println("Usage: java Interpreter <filename>");
      return;
    }

    try {
      Interpreter parser = new Interpreter(new FileInputStream(args[0]));
      parser.Programme();
      System.out.println("Program executed successfully.");
    } catch (FileNotFoundException e) {
      System.out.println("File not found: " + args[0]);
    } catch (ParseException e) {
      System.out.println("Parse error: " + e.getMessage());
      System.out.println("Token: " + e.currentToken.image + " at line " +
                        e.currentToken.beginLine + ", column " + e.currentToken.beginColumn);
    } catch (Exception e) {
      System.out.println("Runtime error: " + e.getMessage());
      e.printStackTrace();
    }
  }

  final public void Programme() throws ParseException {
  Program program = new Program();
  program.declarations = new ArrayList();
  program.functions = new ArrayList();
  program.procedures = new ArrayList();
  Object decl;
  Object func;
  Object proc;
    label_1:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_1;
      }
      decl = DeclarationVar();
                             program.declarations.add(decl);
    }
    label_2:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_2;
      }
      func = DeclarationFunc();
                              program.functions.add(func);
    }
    label_3:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_3;
      }
      proc = DeclarationProc();
                              program.procedures.add(proc);
    }
    program.main = Main();
    executeProgram(program);
  }

  final public Object DeclarationVar() throws ParseException {
  VarDecl decl = new VarDecl();
    decl.type = Type();
    decl.names = ListeIdentifiantVar();
    jj_consume_token(SEMICOLON);
    {if (true) return decl;}
    throw new Error("Missing return statement in function");
  }

  final public List ListeIdentifiantVar() throws ParseException {
  List ids = new ArrayList();
  Token t;
    t = jj_consume_token(IDENTIFIER);
                     ids.add(t.image);
    label_4:
    while (true) {
      if (jj_2_4(2)) {
        ;
      } else {
        break label_4;
      }
      jj_consume_token(COMMA);
      t = jj_consume_token(IDENTIFIER);
                              ids.add(t.image);
    }
    {if (true) return ids;}
    throw new Error("Missing return statement in function");
  }

  final public String Type() throws ParseException {
  String base = "";
    if (jj_2_5(2)) {
      jj_consume_token(INT_TYPE);
                 base = "int";
    } else if (jj_2_6(2)) {
      jj_consume_token(FLOAT_TYPE);
                   base = "float";
    } else if (jj_2_7(2)) {
      jj_consume_token(STRING_TYPE);
                    base = "string";
    } else if (jj_2_8(2)) {
      jj_consume_token(BOOLEAN_TYPE);
                     base = "boolean";
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    if (jj_2_9(2)) {
      jj_consume_token(LBRACK);
      jj_consume_token(RBRACK);
                        base += "[]";
    } else {
      ;
    }
    {if (true) return base;}
    throw new Error("Missing return statement in function");
  }

  final public Object DeclarationFunc() throws ParseException {
  FuncDef func = new FuncDef();
  Token name;
    jj_consume_token(FUN);
    jj_consume_token(LPAREN);
    func.returnType = Type();
    jj_consume_token(RPAREN);
    name = jj_consume_token(IDENTIFIER);
                        func.name = name.image;
    jj_consume_token(LPAREN);
    func.params = ListeParam();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    func.body = BlockContent();
    jj_consume_token(RBRACE);
    {if (true) return func;}
    throw new Error("Missing return statement in function");
  }

  final public Object DeclarationProc() throws ParseException {
  ProcDef proc = new ProcDef();
  Token name;
    jj_consume_token(PROC);
    name = jj_consume_token(IDENTIFIER);
                        proc.name = name.image;
    jj_consume_token(LPAREN);
    proc.params = ListeParam();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    proc.body = BlockContent();
    jj_consume_token(RBRACE);
    {if (true) return proc;}
    throw new Error("Missing return statement in function");
  }

  final public List ListeParam() throws ParseException {
  List params = new ArrayList();
  Object p;
    if (jj_2_11(2)) {
      p = DeclarationParam();
                            params.add(p);
      label_5:
      while (true) {
        if (jj_2_10(2)) {
          ;
        } else {
          break label_5;
        }
        jj_consume_token(COMMA);
        p = DeclarationParam();
                                                                               params.add(p);
      }
    } else {
      ;
    }
    {if (true) return params;}
    throw new Error("Missing return statement in function");
  }

  final public Object DeclarationParam() throws ParseException {
  Param param = new Param();
  Token name;
    param.type = Type();
    name = jj_consume_token(IDENTIFIER);
                        param.name = name.image;
    {if (true) return param;}
    throw new Error("Missing return statement in function");
  }

  final public Object Main() throws ParseException {
  Block block = new Block();
    jj_consume_token(MAIN);
    jj_consume_token(LBRACE);
    block.statements = ListeInstructions();
    jj_consume_token(RBRACE);
    {if (true) return block;}
    throw new Error("Missing return statement in function");
  }

  final public Object BlockContent() throws ParseException {
  Block block = new Block();
  block.statements = new ArrayList();
  Object decl;
  Object stmt;
    label_6:
    while (true) {
      if (jj_2_12(2)) {
        ;
      } else {
        break label_6;
      }
      decl = DeclarationVar();
                             block.statements.add(decl);
    }
    label_7:
    while (true) {
      if (jj_2_13(2)) {
        ;
      } else {
        break label_7;
      }
      stmt = Instruction();
                          block.statements.add(stmt);
    }
    {if (true) return block;}
    throw new Error("Missing return statement in function");
  }

  final public Object Instruction() throws ParseException {
  Object stmt;
    if (jj_2_14(2)) {
      stmt = Affectation();
      jj_consume_token(SEMICOLON);
                                       {if (true) return stmt;}
    } else if (jj_2_15(2)) {
      stmt = Si();
                  {if (true) return stmt;}
    } else if (jj_2_16(2)) {
      stmt = TantQue();
                       {if (true) return stmt;}
    } else if (jj_2_17(2)) {
      stmt = Retour();
      jj_consume_token(SEMICOLON);
                                  {if (true) return stmt;}
    } else if (jj_2_18(2)) {
      stmt = AppelProc();
      jj_consume_token(SEMICOLON);
                                     {if (true) return stmt;}
    } else if (jj_2_19(2)) {
      stmt = Affichage();
      jj_consume_token(SEMICOLON);
                                     {if (true) return stmt;}
    } else if (jj_2_20(2)) {
      stmt = Bloc();
                    {if (true) return stmt;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object Bloc() throws ParseException {
  Block block = new Block();
    jj_consume_token(LBRACE);
    block.statements = ListeInstructions();
    jj_consume_token(RBRACE);
    {if (true) return block;}
    throw new Error("Missing return statement in function");
  }

  final public List ListeInstructions() throws ParseException {
  List stmts = new ArrayList();
  Object stmt;
    label_8:
    while (true) {
      if (jj_2_21(2)) {
        ;
      } else {
        break label_8;
      }
      stmt = Instruction();
                          stmts.add(stmt);
    }
    {if (true) return stmts;}
    throw new Error("Missing return statement in function");
  }

  final public Object Affectation() throws ParseException {
  Assignment assign = new Assignment();
    assign.varName = NomVariable();
    if (jj_2_22(2)) {
      jj_consume_token(LBRACK);
      assign.index = ExprArith();
      jj_consume_token(RBRACK);
    } else {
      ;
    }
    jj_consume_token(ASSIGN);
    assign.value = Expr();
    {if (true) return assign;}
    throw new Error("Missing return statement in function");
  }

  final public String NomVariable() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
    {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final public Object Si() throws ParseException {
  IfStmt ifStmt = new IfStmt();
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    ifStmt.condition = ExprLog();
    jj_consume_token(RPAREN);
    ifStmt.thenBlock = Bloc();
    if (jj_2_23(2)) {
      jj_consume_token(ELSE);
      ifStmt.elseBlock = Bloc();
    } else {
      ;
    }
    {if (true) return ifStmt;}
    throw new Error("Missing return statement in function");
  }

  final public Object TantQue() throws ParseException {
  WhileStmt whileStmt = new WhileStmt();
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    whileStmt.condition = ExprLog();
    jj_consume_token(RPAREN);
    whileStmt.body = Bloc();
    {if (true) return whileStmt;}
    throw new Error("Missing return statement in function");
  }

  final public Object Retour() throws ParseException {
  ReturnStmt ret = new ReturnStmt();
    jj_consume_token(RETURN);
    ret.value = Expr();
    {if (true) return ret;}
    throw new Error("Missing return statement in function");
  }

  final public Object AppelProc() throws ParseException {
  FuncCall call = new FuncCall();
  Token name;
    name = jj_consume_token(IDENTIFIER);
                        call.name = name.image;
    jj_consume_token(LPAREN);
    call.args = ListeArgs();
    jj_consume_token(RPAREN);
    {if (true) return call;}
    throw new Error("Missing return statement in function");
  }

  final public Object Affichage() throws ParseException {
  PrintStmt print = new PrintStmt();
    jj_consume_token(PRINT);
    jj_consume_token(LPAREN);
    print.expression = Expr();
    jj_consume_token(RPAREN);
    {if (true) return print;}
    throw new Error("Missing return statement in function");
  }

  final public Object Expr() throws ParseException {
  Object expr;
    if (jj_2_24(2147483647)) {
      expr = ExprString();
                                                      {if (true) return expr;}
    } else if (jj_2_25(2147483647)) {
      expr = ExprString();
                                                  {if (true) return expr;}
    } else if (jj_2_26(2147483647)) {
      expr = ArrayLiteralExpr();
                                                    {if (true) return expr;}
    } else if (jj_2_27(2147483647)) {
      expr = ExprLog();
                                                                               {if (true) return expr;}
    } else if (jj_2_28(2147483647)) {
      expr = ExprLog();
                                                       {if (true) return expr;}
    } else if (jj_2_29(2147483647)) {
      expr = ExprLog();
                                                     {if (true) return expr;}
    } else if (jj_2_30(2)) {
      expr = ExprArith();
                         {if (true) return expr;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object ExprLog() throws ParseException {
  Object left, right;
  BinaryExpr bin;
    left = EltLog();
    label_9:
    while (true) {
      if (jj_2_31(2)) {
        ;
      } else {
        break label_9;
      }
      jj_consume_token(OR);
      right = EltLog();
      bin = new BinaryExpr();
      bin.operator = "or";
      bin.left = left;
      bin.right = right;
      left = bin;
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Object EltLog() throws ParseException {
  Object left, right;
  BinaryExpr bin;
    left = TermeLog();
    label_10:
    while (true) {
      if (jj_2_32(2)) {
        ;
      } else {
        break label_10;
      }
      jj_consume_token(AND);
      right = TermeLog();
      bin = new BinaryExpr();
      bin.operator = "and";
      bin.left = left;
      bin.right = right;
      left = bin;
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Object TermeLog() throws ParseException {
  Object val;
  UnaryExpr unary;
    if (jj_2_33(2)) {
      jj_consume_token(NOT);
      val = ValLog();
      unary = new UnaryExpr();
      unary.operator = "!";
      unary.operand = val;
      {if (true) return unary;}
    } else if (jj_2_34(2)) {
      val = ValLog();
                     {if (true) return val;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object ValLog() throws ParseException {
  Object expr;
  Token t;
  Object index = null;
  Variable var;
  Literal lit;
    if (jj_2_36(2)) {
      jj_consume_token(TRUE);
      lit = new Literal();
      lit.value = Boolean.TRUE;
      {if (true) return lit;}
    } else if (jj_2_37(2)) {
      jj_consume_token(FALSE);
      lit = new Literal();
      lit.value = Boolean.FALSE;
      {if (true) return lit;}
    } else if (jj_2_38(2)) {
      jj_consume_token(LPAREN);
      expr = ExprLog();
      jj_consume_token(RPAREN);
                                         {if (true) return expr;}
    } else if (jj_2_39(2147483647)) {
      expr = Comp();
                                                                            {if (true) return expr;}
    } else if (jj_2_40(2)) {
      t = jj_consume_token(IDENTIFIER);
      var = new Variable();
      var.name = t.image;
      var.index = null;
      if (jj_2_35(2)) {
        jj_consume_token(LBRACK);
        index = ExprArith();
        jj_consume_token(RBRACK);
                                              var.index = index;
      } else {
        ;
      }
      {if (true) return var;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object Comp() throws ParseException {
  Object left, right;
  String op;
  BinaryExpr bin;
    left = ExprArith();
    op = OpComp();
    right = ExprArith();
    bin = new BinaryExpr();
    bin.operator = op;
    bin.left = left;
    bin.right = right;
    {if (true) return bin;}
    throw new Error("Missing return statement in function");
  }

  final public String OpComp() throws ParseException {
    if (jj_2_41(2)) {
      jj_consume_token(GT);
           {if (true) return ">";}
    } else if (jj_2_42(2)) {
      jj_consume_token(LT);
           {if (true) return "<";}
    } else if (jj_2_43(2)) {
      jj_consume_token(GE);
           {if (true) return ">=";}
    } else if (jj_2_44(2)) {
      jj_consume_token(LE);
           {if (true) return "<=";}
    } else if (jj_2_45(2)) {
      jj_consume_token(EQ);
           {if (true) return "=";}
    } else if (jj_2_46(2)) {
      jj_consume_token(NEQ);
            {if (true) return "!=";}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object ExprArith() throws ParseException {
  Object left, right;
  BinaryExpr bin;
    left = EltArith();
    label_11:
    while (true) {
      if (jj_2_47(2)) {
        ;
      } else {
        break label_11;
      }
      if (jj_2_48(2)) {
        jj_consume_token(PLUS);
        right = EltArith();
        bin = new BinaryExpr();
        bin.operator = "+";
        bin.left = left;
        bin.right = right;
        left = bin;
      } else if (jj_2_49(2)) {
        jj_consume_token(MINUS);
        right = EltArith();
        bin = new BinaryExpr();
        bin.operator = "-";
        bin.left = left;
        bin.right = right;
        left = bin;
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Object EltArith() throws ParseException {
  Object left, right;
  BinaryExpr bin;
    left = TermArith();
    label_12:
    while (true) {
      if (jj_2_50(2)) {
        ;
      } else {
        break label_12;
      }
      if (jj_2_51(2)) {
        jj_consume_token(MULT);
        right = TermArith();
        bin = new BinaryExpr();
        bin.operator = "*";
        bin.left = left;
        bin.right = right;
        left = bin;
      } else if (jj_2_52(2)) {
        jj_consume_token(DIV);
        right = TermArith();
        bin = new BinaryExpr();
        bin.operator = "/";
        bin.left = left;
        bin.right = right;
        left = bin;
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Object TermArith() throws ParseException {
  Object val;
  UnaryExpr unary;
    if (jj_2_53(2)) {
      jj_consume_token(MINUS);
      val = ValArith();
      unary = new UnaryExpr();
      unary.operator = "-";
      unary.operand = val;
      {if (true) return unary;}
    } else if (jj_2_54(2)) {
      val = ValArith();
                       {if (true) return val;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object ValArith() throws ParseException {
  Token t;
  Object val;
  Object index = null;
  Variable var;
  Object arr;
  Literal lit;
    if (jj_2_56(2)) {
      t = jj_consume_token(INTEGER);
      lit = new Literal();
      lit.value = Integer.valueOf(Integer.parseInt(t.image));
      {if (true) return lit;}
    } else if (jj_2_57(2)) {
      t = jj_consume_token(FLOAT_LIT);
      lit = new Literal();
      lit.value = Double.valueOf(Double.parseDouble(t.image));
      {if (true) return lit;}
    } else if (jj_2_58(2)) {
      jj_consume_token(LPAREN);
      val = ExprArith();
      jj_consume_token(RPAREN);
                                          {if (true) return val;}
    } else if (jj_2_59(2)) {
      arr = ArrayLiteralExpr();
                                            {if (true) return arr;}
    } else if (jj_2_60(2)) {
      t = jj_consume_token(IDENTIFIER);
      var = new Variable();
      var.name = t.image;
      var.index = null;
      if (jj_2_55(2)) {
        jj_consume_token(LBRACK);
        index = ExprArith();
        jj_consume_token(RBRACK);
                                              var.index = index;
      } else {
        ;
      }
      {if (true) return var;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object ArrayLiteralExpr() throws ParseException {
  ArrayLiteral arr = new ArrayLiteral();
  arr.elements = new ArrayList();
  Object elem;
    jj_consume_token(LBRACK);
    if (jj_2_62(2)) {
      elem = Expr();
                    arr.elements.add(elem);
      label_13:
      while (true) {
        if (jj_2_61(2)) {
          ;
        } else {
          break label_13;
        }
        jj_consume_token(COMMA);
        elem = Expr();
                             arr.elements.add(elem);
      }
    } else {
      ;
    }
    jj_consume_token(RBRACK);
    {if (true) return arr;}
    throw new Error("Missing return statement in function");
  }

  final public Object ExprString() throws ParseException {
  Object result;
  Object next;
  BinaryExpr bin;
  InputExpr input;
    if (jj_2_64(2)) {
      jj_consume_token(INPUT);
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
      input = new InputExpr();
      {if (true) return input;}
    } else if (jj_2_65(2)) {
      result = TermeString();
      label_14:
      while (true) {
        if (jj_2_63(2)) {
          ;
        } else {
          break label_14;
        }
        jj_consume_token(PLUS);
        next = TermeString();
        bin = new BinaryExpr();
        bin.operator = "+";
        bin.left = result;
        bin.right = next;
        result = bin;
      }
      {if (true) return result;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object TermeString() throws ParseException {
  Token t;
  Object val;
  Variable var;
  Literal lit;
    if (jj_2_66(2)) {
      t = jj_consume_token(STRING_LIT);
      lit = new Literal();
      lit.value = t.image.substring(1, t.image.length() - 1);
      {if (true) return lit;}
    } else if (jj_2_67(2)) {
      jj_consume_token(LPAREN);
      val = ExprArith();
      jj_consume_token(RPAREN);
                                          {if (true) return val;}
    } else if (jj_2_68(2)) {
      t = jj_consume_token(IDENTIFIER);
      var = new Variable();
      var.name = t.image;
      var.index = null;
      {if (true) return var;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public List ListeArgs() throws ParseException {
  List args = new ArrayList();
  Object arg;
    if (jj_2_70(2)) {
      arg = Expr();
                   args.add(arg);
      label_15:
      while (true) {
        if (jj_2_69(2)) {
          ;
        } else {
          break label_15;
        }
        jj_consume_token(COMMA);
        arg = Expr();
                            args.add(arg);
      }
    } else {
      ;
    }
    {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  private boolean jj_2_39(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  private boolean jj_2_40(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  private boolean jj_2_41(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  private boolean jj_2_42(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_42(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  private boolean jj_2_43(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_43(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  private boolean jj_2_44(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_44(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(43, xla); }
  }

  private boolean jj_2_45(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_45(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(44, xla); }
  }

  private boolean jj_2_46(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_46(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(45, xla); }
  }

  private boolean jj_2_47(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_47(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(46, xla); }
  }

  private boolean jj_2_48(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_48(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(47, xla); }
  }

  private boolean jj_2_49(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_49(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(48, xla); }
  }

  private boolean jj_2_50(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_50(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(49, xla); }
  }

  private boolean jj_2_51(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_51(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(50, xla); }
  }

  private boolean jj_2_52(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_52(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(51, xla); }
  }

  private boolean jj_2_53(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_53(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(52, xla); }
  }

  private boolean jj_2_54(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_54(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(53, xla); }
  }

  private boolean jj_2_55(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_55(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(54, xla); }
  }

  private boolean jj_2_56(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_56(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(55, xla); }
  }

  private boolean jj_2_57(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_57(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(56, xla); }
  }

  private boolean jj_2_58(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_58(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(57, xla); }
  }

  private boolean jj_2_59(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_59(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(58, xla); }
  }

  private boolean jj_2_60(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_60(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(59, xla); }
  }

  private boolean jj_2_61(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_61(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(60, xla); }
  }

  private boolean jj_2_62(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_62(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(61, xla); }
  }

  private boolean jj_2_63(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_63(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(62, xla); }
  }

  private boolean jj_2_64(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_64(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(63, xla); }
  }

  private boolean jj_2_65(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_65(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(64, xla); }
  }

  private boolean jj_2_66(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_66(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(65, xla); }
  }

  private boolean jj_2_67(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_67(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(66, xla); }
  }

  private boolean jj_2_68(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_68(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(67, xla); }
  }

  private boolean jj_2_69(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_69(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(68, xla); }
  }

  private boolean jj_2_70(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_70(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(69, xla); }
  }

  private boolean jj_3_69() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_40() {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_35()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_70() {
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_69()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3_38() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_3R_39()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_37() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_36()) {
    jj_scanpos = xsp;
    if (jj_3_37()) {
    jj_scanpos = xsp;
    if (jj_3_38()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3_40()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3_36() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3_68() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_67() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_28()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_66()) {
    jj_scanpos = xsp;
    if (jj_3_67()) {
    jj_scanpos = xsp;
    if (jj_3_68()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_66() {
    if (jj_scan_token(STRING_LIT)) return true;
    return false;
  }

  private boolean jj_3_34() {
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(PROC)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_31() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_33()) {
    jj_scanpos = xsp;
    if (jj_3_34()) return true;
    }
    return false;
  }

  private boolean jj_3_33() {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3_63() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3_65() {
    if (jj_3R_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_63()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(FUN)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_64()) {
    jj_scanpos = xsp;
    if (jj_3_65()) return true;
    }
    return false;
  }

  private boolean jj_3_64() {
    if (jj_scan_token(INPUT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_32() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(LBRACK)) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_31()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_32()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_8() {
    if (jj_scan_token(BOOLEAN_TYPE)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_scan_token(STRING_TYPE)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(FLOAT_TYPE)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(INT_TYPE)) return true;
    return false;
  }

  private boolean jj_3_61() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) return true;
    }
    }
    }
    xsp = jj_scanpos;
    if (jj_3_9()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_62() {
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_61()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(LBRACK)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_62()) jj_scanpos = xsp;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  private boolean jj_3_31() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_29() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(34)) return true;
    }
    }
    return false;
  }

  private boolean jj_3_27() {
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_scan_token(LBRACK)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_25() {
    if (jj_scan_token(STRING_LIT)) return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_scan_token(INPUT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_55() {
    if (jj_scan_token(LBRACK)) return true;
    if (jj_3R_28()) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  private boolean jj_3_30() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_36()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_3R_39()) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3_60() {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_55()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_51()) return true;
    return false;
  }

  private boolean jj_3_59() {
    if (jj_3R_36()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_51()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3_30()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_58() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_28()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_57() {
    if (jj_scan_token(FLOAT_LIT)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(PRINT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_56()) {
    jj_scanpos = xsp;
    if (jj_3_57()) {
    jj_scanpos = xsp;
    if (jj_3_58()) {
    jj_scanpos = xsp;
    if (jj_3_59()) {
    jj_scanpos = xsp;
    if (jj_3_60()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_56() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_54() {
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(RETURN)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_53()) {
    jj_scanpos = xsp;
    if (jj_3_54()) return true;
    }
    return false;
  }

  private boolean jj_3_53() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_52() {
    if (jj_scan_token(DIV)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_51()) {
    jj_scanpos = xsp;
    if (jj_3_52()) return true;
    }
    return false;
  }

  private boolean jj_3_51() {
    if (jj_scan_token(MULT)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_34()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_50()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_22() {
    if (jj_scan_token(LBRACK)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_41()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_22()) jj_scanpos = xsp;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_49() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_21()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_47() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_48()) {
    jj_scanpos = xsp;
    if (jj_3_49()) return true;
    }
    return false;
  }

  private boolean jj_3_48() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_33()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_47()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_42()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3_46() {
    if (jj_scan_token(NEQ)) return true;
    return false;
  }

  private boolean jj_3_45() {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  private boolean jj_3_20() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_44() {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3_43() {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3_42() {
    if (jj_scan_token(LT)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_41()) {
    jj_scanpos = xsp;
    if (jj_3_42()) {
    jj_scanpos = xsp;
    if (jj_3_43()) {
    jj_scanpos = xsp;
    if (jj_3_44()) {
    jj_scanpos = xsp;
    if (jj_3_45()) {
    jj_scanpos = xsp;
    if (jj_3_46()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_17() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3_41() {
    if (jj_scan_token(GT)) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) {
    jj_scanpos = xsp;
    if (jj_3_19()) {
    jj_scanpos = xsp;
    if (jj_3_20()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_3R_28()) return true;
    if (jj_3R_52()) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_39() {
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_35() {
    if (jj_scan_token(LBRACK)) return true;
    if (jj_3R_28()) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public InterpreterTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[70];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Interpreter(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Interpreter(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new InterpreterTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Interpreter(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new InterpreterTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Interpreter(InterpreterTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(InterpreterTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[47];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 47; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 70; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
            case 41: jj_3_42(); break;
            case 42: jj_3_43(); break;
            case 43: jj_3_44(); break;
            case 44: jj_3_45(); break;
            case 45: jj_3_46(); break;
            case 46: jj_3_47(); break;
            case 47: jj_3_48(); break;
            case 48: jj_3_49(); break;
            case 49: jj_3_50(); break;
            case 50: jj_3_51(); break;
            case 51: jj_3_52(); break;
            case 52: jj_3_53(); break;
            case 53: jj_3_54(); break;
            case 54: jj_3_55(); break;
            case 55: jj_3_56(); break;
            case 56: jj_3_57(); break;
            case 57: jj_3_58(); break;
            case 58: jj_3_59(); break;
            case 59: jj_3_60(); break;
            case 60: jj_3_61(); break;
            case 61: jj_3_62(); break;
            case 62: jj_3_63(); break;
            case 63: jj_3_64(); break;
            case 64: jj_3_65(); break;
            case 65: jj_3_66(); break;
            case 66: jj_3_67(); break;
            case 67: jj_3_68(); break;
            case 68: jj_3_69(); break;
            case 69: jj_3_70(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
