/* Generated By:JavaCC: Do not edit this line. Interpreter.java */
import java.util.*;
import java.io.*;

public class Interpreter implements InterpreterConstants {
  private Map globalVars = new HashMap();
  private Map functions = new HashMap();
  private Map procedures = new HashMap();
  private Stack scopes = new Stack();

  public static void main(String[] args) throws Exception {
    if (args.length == 0) {
      System.out.println("Usage: java Interpreter <filename>");
      return;
    }
    Interpreter parser = new Interpreter(new FileInputStream(args[0]));
    parser.Programme();
    System.out.println("Program executed successfully.");
  }

  private void pushScope() {
    scopes.push(new HashMap());
  }

  private void popScope() {
    if (!scopes.isEmpty()) scopes.pop();
  }

  private void setVar(String name, Object value) {
    if (!scopes.isEmpty()) {
      ((Map)scopes.peek()).put(name, value);
    } else {
      globalVars.put(name, value);
    }
  }

  private Object getVar(String name) {
    for (int i = scopes.size() - 1; i >= 0; i--) {
      Map scope = (Map)scopes.get(i);
      if (scope.containsKey(name)) {
        return scope.get(name);
      }
    }
    return globalVars.get(name);
  }

  private Object getDefaultValue(String type) {
    switch(type) {
      case "int": return Integer.valueOf(0);
      case "float": return Double.valueOf(0.0);
      case "string": return "";
      case "boolean": return Boolean.FALSE;
      case "int[]": return new ArrayList();
      case "float[]": return new ArrayList();
      case "string[]": return new ArrayList();
      case "boolean[]": return new ArrayList();
      default: return null;
    }
  }

  static class FunctionDef {
    String returnType;
    List params;

    FunctionDef(String returnType, List params) {
      this.returnType = returnType;
      this.params = params;
    }
  }

  static class ProcDef {
    List params;

    ProcDef(List params) {
      this.params = params;
    }
  }

  static class Param {
    String type;
    String name;

    Param(String type, String name) {
      this.type = type;
      this.name = name;
    }
  }

  static class ReturnValue extends RuntimeException {
    Object value;
    ReturnValue(Object value) {
      this.value = value;
    }
  }

  final public void Programme() throws ParseException {
    ListeDeclarations();
    ListeFonctionsEtProcs();
    Main();
    jj_consume_token(0);
  }

  final public void ListeDeclarations() throws ParseException {
    label_1:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_1;
      }
      DeclarationVar();
    }
  }

  final public void DeclarationVar() throws ParseException {
  String type;
  List ids = new ArrayList();
    type = Type();
    ListeIdentifiantVar(ids);
    jj_consume_token(SEMICOLON);
    for (int i = 0; i < ids.size(); i++) {
      String id = (String)ids.get(i);
      Object initVal = getDefaultValue(type);
      setVar(id, initVal);
    }
  }

  final public void ListeIdentifiantVar(List ids) throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
                     ids.add(t.image);
    label_2:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_2;
      }
      jj_consume_token(COMMA);
      t = jj_consume_token(IDENTIFIER);
                              ids.add(t.image);
    }
  }

  final public String Type() throws ParseException {
  String base = "";
    if (jj_2_3(2)) {
      jj_consume_token(INT_TYPE);
                 base = "int";
    } else if (jj_2_4(2)) {
      jj_consume_token(FLOAT_TYPE);
                   base = "float";
    } else if (jj_2_5(2)) {
      jj_consume_token(STRING_TYPE);
                    base = "string";
    } else if (jj_2_6(2)) {
      jj_consume_token(BOOLEAN_TYPE);
                     base = "boolean";
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    if (jj_2_7(2)) {
      jj_consume_token(LBRACK);
      jj_consume_token(RBRACK);
                        base += "[]";
    } else {
      ;
    }
    {if (true) return base;}
    throw new Error("Missing return statement in function");
  }

  final public void ListeFonctionsEtProcs() throws ParseException {
    label_3:
    while (true) {
      if (jj_2_8(2)) {
        ;
      } else {
        break label_3;
      }
      if (jj_2_9(3)) {
        DeclarationFunc();
      } else if (jj_2_10(2)) {
        DeclarationProc();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void DeclarationFunc() throws ParseException {
  String returnType;
  Token name;
  List params;
    jj_consume_token(FUN);
    jj_consume_token(LPAREN);
    returnType = Type();
    jj_consume_token(RPAREN);
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(LPAREN);
    params = ListeParam();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
      FunctionDef func = new FunctionDef(returnType, params);
      functions.put(name.image, func);
      pushScope();
      for (int i = 0; i < params.size(); i++) {
        Param p = (Param)params.get(i);
        setVar(p.name, getDefaultValue(p.type));
      }
    ListeDeclarations();
    ListeInstructions();
      popScope();
    jj_consume_token(RBRACE);
  }

  final public void DeclarationProc() throws ParseException {
  Token name;
  List params;
    jj_consume_token(PROC);
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(LPAREN);
    params = ListeParam();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
      ProcDef proc = new ProcDef(params);
      procedures.put(name.image, proc);
      pushScope();
      for (int i = 0; i < params.size(); i++) {
        Param p = (Param)params.get(i);
        setVar(p.name, getDefaultValue(p.type));
      }
    ListeDeclarations();
    ListeInstructions();
      popScope();
    jj_consume_token(RBRACE);
  }

  final public List ListeParam() throws ParseException {
  List params = new ArrayList();
  Param p;
    if (jj_2_12(2)) {
      p = DeclarationParam();
                             params.add(p);
      label_4:
      while (true) {
        if (jj_2_11(2)) {
          ;
        } else {
          break label_4;
        }
        jj_consume_token(COMMA);
        p = DeclarationParam();
                                      params.add(p);
      }
    } else {
      ;
    }
    {if (true) return params;}
    throw new Error("Missing return statement in function");
  }

  final public Param DeclarationParam() throws ParseException {
  String type;
  Token name;
    type = Type();
    name = jj_consume_token(IDENTIFIER);
    {if (true) return new Param(type, name.image);}
    throw new Error("Missing return statement in function");
  }

  final public void Main() throws ParseException {
    jj_consume_token(MAIN);
    jj_consume_token(LBRACE);
      pushScope();
    ListeDeclarations();
    ListeInstructions();
      popScope();
    jj_consume_token(RBRACE);
  }

  final public void ListeInstructions() throws ParseException {
    label_5:
    while (true) {
      if (jj_2_13(2)) {
        ;
      } else {
        break label_5;
      }
      Instruction();
    }
  }

  final public void Instruction() throws ParseException {
    if (jj_2_14(3)) {
      Affectation();
      jj_consume_token(SEMICOLON);
    } else if (jj_2_15(2)) {
      Si();
    } else if (jj_2_16(2)) {
      TantQue();
    } else if (jj_2_17(2)) {
      Retour();
      jj_consume_token(SEMICOLON);
    } else if (jj_2_18(3)) {
      AppelProc();
      jj_consume_token(SEMICOLON);
    } else if (jj_2_19(2)) {
      Affichage();
      jj_consume_token(SEMICOLON);
    } else if (jj_2_20(2)) {
      Bloc();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Bloc() throws ParseException {
    jj_consume_token(LBRACE);
      pushScope();
    ListeInstructions();
      popScope();
    jj_consume_token(RBRACE);
  }

  final public void Affectation() throws ParseException {
  String varName;
  Object index = null;
  Object value;
    varName = NomVariable();
    if (jj_2_21(2)) {
      jj_consume_token(LBRACK);
      index = ExprArith();
      jj_consume_token(RBRACK);
    } else {
      ;
    }
    jj_consume_token(ASSIGN);
    value = Expr();
    if (index != null) {
      Object var = getVar(varName);
      if (var instanceof List) {
        int idx = ((Number)index).intValue();
        ((List)var).set(idx, value);
      }
    } else {
      setVar(varName, value);
    }
  }

  final public String NomVariable() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
    {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final public void Si() throws ParseException {
  boolean cond;
  boolean elsePresent = false;
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    cond = ExprLog();
    jj_consume_token(RPAREN);
    if (jj_2_22(2)) {

    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    Bloc();
      if (!cond) {
        // Skip this block
      }
    if (jj_2_23(2)) {
      jj_consume_token(ELSE);
      Bloc();
        if (cond) {
          // Skip else block
        }
    } else {
      ;
    }
  }

  final public void TantQue() throws ParseException {
  boolean cond;
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    cond = ExprLog();
    jj_consume_token(RPAREN);
    Bloc();
  }

  final public void Retour() throws ParseException {
  Object value;
    jj_consume_token(RETURN);
    value = Expr();
    {if (true) throw new ReturnValue(value);}
  }

  final public void AppelProc() throws ParseException {
  Token name;
  List args;
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(LPAREN);
    args = ListeArgs();
    jj_consume_token(RPAREN);
  }

  final public void Affichage() throws ParseException {
  Object value;
    jj_consume_token(PRINT);
    jj_consume_token(LPAREN);
    value = Expr();
    jj_consume_token(RPAREN);
    System.out.println(value);
  }

  final public Object Expr() throws ParseException {
  Object val;
    if (jj_2_24(3)) {
      val = ExprArith();
                                     {if (true) return val;}
    } else if (jj_2_25(3)) {
      val = ExprLog();
                                   {if (true) return val;}
    } else if (jj_2_26(2)) {
      val = ExprString();
                         {if (true) return val;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public boolean ExprLog() throws ParseException {
  boolean left, right;
    left = EltLog();
    label_6:
    while (true) {
      if (jj_2_27(2)) {
        ;
      } else {
        break label_6;
      }
      jj_consume_token(OR);
      right = EltLog();
                            left = left || right;
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public boolean EltLog() throws ParseException {
  boolean left, right;
    left = TermeLog();
    label_7:
    while (true) {
      if (jj_2_28(2)) {
        ;
      } else {
        break label_7;
      }
      jj_consume_token(AND);
      right = TermeLog();
                               left = left && right;
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public boolean TermeLog() throws ParseException {
  boolean val;
    if (jj_2_29(2)) {
      jj_consume_token(NOT);
      val = ValLog();
                         {if (true) return !val;}
    } else if (jj_2_30(2)) {
      val = ValLog();
                   {if (true) return val;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public boolean ValLog() throws ParseException {
  boolean val;
  Token t;
  Object expr;
    if (jj_2_32(2)) {
      jj_consume_token(TRUE);
           {if (true) return true;}
    } else if (jj_2_33(2)) {
      jj_consume_token(FALSE);
            {if (true) return false;}
    } else if (jj_2_34(2)) {
      jj_consume_token(LPAREN);
      val = ExprLog();
      jj_consume_token(RPAREN);
                                      {if (true) return val;}
    } else if (jj_2_35(2147483647)) {
      val = Comp();
                                   {if (true) return val;}
    } else if (jj_2_36(2)) {
      t = jj_consume_token(IDENTIFIER);
      if (jj_2_31(2)) {
        jj_consume_token(LBRACK);
        expr = ExprArith();
        jj_consume_token(RBRACK);
      Object var = getVar(t.image);
      if (var instanceof List) {
        int idx = ((Number)expr).intValue();
        Object elem = ((List)var).get(idx);
        if (elem instanceof Boolean) {if (true) return (Boolean)elem;}
      }
      {if (true) return false;}
      } else {
      Object v = getVar(t.image);
      if (v instanceof Boolean) {if (true) return (Boolean)v;}
      {if (true) return false;}
      }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public boolean Comp() throws ParseException {
  Object left, right;
  String op;
    left = ExprArith();
    op = OpComp();
    right = ExprArith();
      double l = ((Number)left).doubleValue();
      double r = ((Number)right).doubleValue();
      switch(op) {
        case ">": {if (true) return l > r;}
        case "<": {if (true) return l < r;}
        case ">=": {if (true) return l >= r;}
        case "<=": {if (true) return l <= r;}
        case "=": {if (true) return l == r;}
        case "!=": {if (true) return l != r;}
        default: {if (true) return false;}
      }
    throw new Error("Missing return statement in function");
  }

  final public String OpComp() throws ParseException {
    if (jj_2_37(2)) {
      jj_consume_token(GT);
         {if (true) return ">";}
    } else if (jj_2_38(2)) {
      jj_consume_token(LT);
         {if (true) return "<";}
    } else if (jj_2_39(2)) {
      jj_consume_token(GE);
         {if (true) return ">=";}
    } else if (jj_2_40(2)) {
      jj_consume_token(LE);
         {if (true) return "<=";}
    } else if (jj_2_41(2)) {
      jj_consume_token(EQ);
         {if (true) return "=";}
    } else if (jj_2_42(2)) {
      jj_consume_token(NEQ);
          {if (true) return "!=";}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object ExprArith() throws ParseException {
  Object left, right;
    left = EltArith();
    label_8:
    while (true) {
      if (jj_2_43(2)) {
        ;
      } else {
        break label_8;
      }
      if (jj_2_44(2)) {
        jj_consume_token(PLUS);
        right = EltArith();
      left = ((Number)left).doubleValue() + ((Number)right).doubleValue();
      } else if (jj_2_45(2)) {
        jj_consume_token(MINUS);
        right = EltArith();
      left = ((Number)left).doubleValue() - ((Number)right).doubleValue();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Object EltArith() throws ParseException {
  Object left, right;
    left = TermArith();
    label_9:
    while (true) {
      if (jj_2_46(2)) {
        ;
      } else {
        break label_9;
      }
      if (jj_2_47(2)) {
        jj_consume_token(MULT);
        right = TermArith();
      left = ((Number)left).doubleValue() * ((Number)right).doubleValue();
      } else if (jj_2_48(2)) {
        jj_consume_token(DIV);
        right = TermArith();
      left = ((Number)left).doubleValue() / ((Number)right).doubleValue();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Object TermArith() throws ParseException {
  Object val;
    if (jj_2_49(2)) {
      jj_consume_token(MINUS);
      val = ValArith();
    {if (true) return -((Number)val).doubleValue();}
    } else if (jj_2_50(2)) {
      val = ValArith();
                     {if (true) return val;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object ValArith() throws ParseException {
  Token t;
  Object val;
  Object expr;
    if (jj_2_52(2)) {
      t = jj_consume_token(INTEGER);
                  {if (true) return Integer.parseInt(t.image);}
    } else if (jj_2_53(2)) {
      t = jj_consume_token(FLOAT_LIT);
                    {if (true) return Double.parseDouble(t.image);}
    } else if (jj_2_54(2)) {
      jj_consume_token(LPAREN);
      val = ExprArith();
      jj_consume_token(RPAREN);
                                        {if (true) return val;}
    } else if (jj_2_55(2)) {
      t = jj_consume_token(IDENTIFIER);
      if (jj_2_51(2)) {
        jj_consume_token(LBRACK);
        expr = ExprArith();
        jj_consume_token(RBRACK);
      Object var = getVar(t.image);
      if (var instanceof List) {
        int idx = ((Number)expr).intValue();
        {if (true) return ((List)var).get(idx);}
      }
      {if (true) return 0;}
      } else {
      Object v = getVar(t.image);
      if (v instanceof Number) {if (true) return v;}
      {if (true) return 0;}
      }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object ExprString() throws ParseException {
  Object result;
  Object next;
    if (jj_2_57(2)) {
      jj_consume_token(INPUT);
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
    Scanner sc = new Scanner(System.in);
    {if (true) return sc.nextLine();}
    } else if (jj_2_58(2)) {
      result = TermeString();
      label_10:
      while (true) {
        if (jj_2_56(2)) {
          ;
        } else {
          break label_10;
        }
        jj_consume_token(PLUS);
        next = TermeString();
      result = result.toString() + next.toString();
      }
    {if (true) return result;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Object TermeString() throws ParseException {
  Token t;
  Object val;
    if (jj_2_59(2)) {
      t = jj_consume_token(STRING_LIT);
    String s = t.image;
    {if (true) return s.substring(1, s.length() - 1);}
    } else if (jj_2_60(2)) {
      jj_consume_token(LPAREN);
      val = ExprArith();
      jj_consume_token(RPAREN);
    {if (true) return val.toString();}
    } else if (jj_2_61(2)) {
      t = jj_consume_token(IDENTIFIER);
    Object v = getVar(t.image);
    {if (true) return v != null ? v.toString() : "";}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public List ListeArgs() throws ParseException {
  List args = new ArrayList();
  Object arg;
    if (jj_2_63(2)) {
      arg = Expr();
                   args.add(arg);
      label_11:
      while (true) {
        if (jj_2_62(2)) {
          ;
        } else {
          break label_11;
        }
        jj_consume_token(COMMA);
        arg = Expr();
                            args.add(arg);
      }
    } else {
      ;
    }
    {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  private boolean jj_2_39(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  private boolean jj_2_40(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  private boolean jj_2_41(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  private boolean jj_2_42(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_42(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  private boolean jj_2_43(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_43(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  private boolean jj_2_44(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_44(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(43, xla); }
  }

  private boolean jj_2_45(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_45(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(44, xla); }
  }

  private boolean jj_2_46(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_46(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(45, xla); }
  }

  private boolean jj_2_47(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_47(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(46, xla); }
  }

  private boolean jj_2_48(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_48(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(47, xla); }
  }

  private boolean jj_2_49(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_49(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(48, xla); }
  }

  private boolean jj_2_50(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_50(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(49, xla); }
  }

  private boolean jj_2_51(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_51(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(50, xla); }
  }

  private boolean jj_2_52(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_52(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(51, xla); }
  }

  private boolean jj_2_53(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_53(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(52, xla); }
  }

  private boolean jj_2_54(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_54(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(53, xla); }
  }

  private boolean jj_2_55(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_55(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(54, xla); }
  }

  private boolean jj_2_56(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_56(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(55, xla); }
  }

  private boolean jj_2_57(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_57(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(56, xla); }
  }

  private boolean jj_2_58(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_58(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(57, xla); }
  }

  private boolean jj_2_59(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_59(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(58, xla); }
  }

  private boolean jj_2_60(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_60(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(59, xla); }
  }

  private boolean jj_2_61(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_61(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(60, xla); }
  }

  private boolean jj_2_62(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_62(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(61, xla); }
  }

  private boolean jj_2_63(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_63(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(62, xla); }
  }

  private boolean jj_3_58() {
    if (jj_3R_36()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_56()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_57()) {
    jj_scanpos = xsp;
    if (jj_3_58()) return true;
    }
    return false;
  }

  private boolean jj_3_57() {
    if (jj_scan_token(INPUT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_3R_38()) return true;
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_51() {
    if (jj_scan_token(LBRACK)) return true;
    if (jj_3R_24()) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  private boolean jj_3_55() {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_51()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    }
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_54() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_24()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_53() {
    if (jj_scan_token(FLOAT_LIT)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_52()) {
    jj_scanpos = xsp;
    if (jj_3_53()) {
    jj_scanpos = xsp;
    if (jj_3_54()) {
    jj_scanpos = xsp;
    if (jj_3_55()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3_52() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_50() {
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_49()) {
    jj_scanpos = xsp;
    if (jj_3_50()) return true;
    }
    return false;
  }

  private boolean jj_3_49() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3_48() {
    if (jj_scan_token(DIV)) return true;
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_47()) {
    jj_scanpos = xsp;
    if (jj_3_48()) return true;
    }
    return false;
  }

  private boolean jj_3_47() {
    if (jj_scan_token(MULT)) return true;
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_scan_token(LBRACK)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_33()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_46()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_3R_40()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_21()) jj_scanpos = xsp;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_45() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3_43() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_44()) {
    jj_scanpos = xsp;
    if (jj_3_45()) return true;
    }
    return false;
  }

  private boolean jj_3_44() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_42()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_3R_32()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_43()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_20() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_42() {
    if (jj_scan_token(NEQ)) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3_41() {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3_40() {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) {
    jj_scanpos = xsp;
    if (jj_3_19()) {
    jj_scanpos = xsp;
    if (jj_3_20()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_39() {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  private boolean jj_3_38() {
    if (jj_scan_token(LT)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_37()) {
    jj_scanpos = xsp;
    if (jj_3_38()) {
    jj_scanpos = xsp;
    if (jj_3_39()) {
    jj_scanpos = xsp;
    if (jj_3_40()) {
    jj_scanpos = xsp;
    if (jj_3_41()) {
    jj_scanpos = xsp;
    if (jj_3_42()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_37() {
    if (jj_scan_token(GT)) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_13()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_3R_38()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_24()) return true;
    if (jj_3R_44()) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_31() {
    return false;
  }

  private boolean jj_3_35() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_31() {
    if (jj_scan_token(LBRACK)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3_36() {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_31()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3_34() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_25()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_33() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_32()) {
    jj_scanpos = xsp;
    if (jj_3_33()) {
    jj_scanpos = xsp;
    if (jj_3_34()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3_36()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_32() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(PROC)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_30() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_29()) {
    jj_scanpos = xsp;
    if (jj_3_30()) return true;
    }
    return false;
  }

  private boolean jj_3_29() {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_28() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_28()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_27() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(FUN)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3_62() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_27()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_63() {
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_62()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_63()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) return true;
    }
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_24()) {
    jj_scanpos = xsp;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_7() {
    if (jj_scan_token(LBRACK)) return true;
    if (jj_scan_token(RBRACK)) return true;
    return false;
  }

  private boolean jj_3_61() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(PRINT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(BOOLEAN_TYPE)) return true;
    return false;
  }

  private boolean jj_3_60() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(STRING_TYPE)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(FLOAT_TYPE)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(INT_TYPE)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_59()) {
    jj_scanpos = xsp;
    if (jj_3_60()) {
    jj_scanpos = xsp;
    if (jj_3_61()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_59() {
    if (jj_scan_token(STRING_LIT)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    }
    }
    }
    xsp = jj_scanpos;
    if (jj_3_7()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_41()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_56() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_36()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(RETURN)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public InterpreterTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[63];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Interpreter(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Interpreter(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new InterpreterTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Interpreter(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new InterpreterTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Interpreter(InterpreterTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(InterpreterTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[47];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 47; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 63; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
            case 41: jj_3_42(); break;
            case 42: jj_3_43(); break;
            case 43: jj_3_44(); break;
            case 44: jj_3_45(); break;
            case 45: jj_3_46(); break;
            case 46: jj_3_47(); break;
            case 47: jj_3_48(); break;
            case 48: jj_3_49(); break;
            case 49: jj_3_50(); break;
            case 50: jj_3_51(); break;
            case 51: jj_3_52(); break;
            case 52: jj_3_53(); break;
            case 53: jj_3_54(); break;
            case 54: jj_3_55(); break;
            case 55: jj_3_56(); break;
            case 56: jj_3_57(); break;
            case 57: jj_3_58(); break;
            case 58: jj_3_59(); break;
            case 59: jj_3_60(); break;
            case 60: jj_3_61(); break;
            case 61: jj_3_62(); break;
            case 62: jj_3_63(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
