/* Generated By:JavaCC: Do not edit this line. InterpreterConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InterpreterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUN = 6;
  /** RegularExpression Id. */
  int PROC = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int INPUT = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int INT_TYPE = 17;
  /** RegularExpression Id. */
  int FLOAT_TYPE = 18;
  /** RegularExpression Id. */
  int STRING_TYPE = 19;
  /** RegularExpression Id. */
  int BOOLEAN_TYPE = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int ASSIGN = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int NEQ = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int GT = 27;
  /** RegularExpression Id. */
  int LE = 28;
  /** RegularExpression Id. */
  int GE = 29;
  /** RegularExpression Id. */
  int PLUS = 30;
  /** RegularExpression Id. */
  int MINUS = 31;
  /** RegularExpression Id. */
  int MULT = 32;
  /** RegularExpression Id. */
  int DIV = 33;
  /** RegularExpression Id. */
  int NOT = 34;
  /** RegularExpression Id. */
  int LPAREN = 35;
  /** RegularExpression Id. */
  int RPAREN = 36;
  /** RegularExpression Id. */
  int LBRACE = 37;
  /** RegularExpression Id. */
  int RBRACE = 38;
  /** RegularExpression Id. */
  int LBRACK = 39;
  /** RegularExpression Id. */
  int RBRACK = 40;
  /** RegularExpression Id. */
  int SEMICOLON = 41;
  /** RegularExpression Id. */
  int COMMA = 42;
  /** RegularExpression Id. */
  int FLOAT_LIT = 43;
  /** RegularExpression Id. */
  int INTEGER = 44;
  /** RegularExpression Id. */
  int STRING_LIT = 45;
  /** RegularExpression Id. */
  int IDENTIFIER = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"fun\"",
    "\"proc\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"print\"",
    "\"input\"",
    "\"true\"",
    "\"false\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"boolean\"",
    "\"and\"",
    "\"or\"",
    "\":=\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "<FLOAT_LIT>",
    "<INTEGER>",
    "<STRING_LIT>",
    "<IDENTIFIER>",
  };

}
